package com.xpedx.sterling.rcp.pca.sharedTasks.shiptolookup;

import org.eclipse.swt.SWT;
import org.eclipse.swt.events.MouseAdapter;
import org.eclipse.swt.events.MouseEvent;
import org.eclipse.swt.layout.FillLayout;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Combo;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Group;
import org.eclipse.swt.widgets.Label;
import org.eclipse.swt.widgets.Table;
import org.eclipse.swt.widgets.TableColumn;
import org.eclipse.swt.widgets.Text;
import org.w3c.dom.Element;

import com.xpedx.sterling.rcp.pca.util.XPXPaginationBehavior;
import com.xpedx.sterling.rcp.pca.util.XPXPaginationComposite;
import com.xpedx.sterling.rcp.pca.util.XPXUtils;
import com.yantra.yfc.rcp.IYRCComposite;
import com.yantra.yfc.rcp.IYRCPanelHolder;
import com.yantra.yfc.rcp.YRCComboBindingData;
import com.yantra.yfc.rcp.YRCConstants;
import com.yantra.yfc.rcp.YRCTableBindingData;
import com.yantra.yfc.rcp.YRCTblClmBindingData;
import com.yantra.yfc.rcp.YRCXmlUtils;

/**
 * @author Manas
 *
 * Generated by Sterling RCP Tools
 * Copyright � 2005, 2006 Sterling Commerce, Inc. All Rights Reserved.
 */
public class XPXShowListOfUOMPanel extends XPXPaginationComposite implements IYRCComposite{
	
	private Composite pnlRoot = null;
    private XPXShowListOfUOMPanelBehaviour myBehavior;
	private Element elePageInput;
	private Group pnlResults;
	Table tblResults;
	public Element eleSelected;
	private String isMil;
	private Composite pnlProfileInfo;
	private Group grpSearchFields;
	private Group grpBtnFields;
	private Label lblItemName;
	private Text txtItemName;
	private Label lblUOMID;
	private Combo uomIDCombo;
	public String itemID;
    public static final String FORM_ID = "com.xpedx.sterling.rcp.pca.sharedTasks.shiptolookup.XPXShowListOfUOMPanel";

	public XPXShowListOfUOMPanel(Composite parent, int style, Element inputObject) {
		super(parent, style);
		elePageInput = (Element) inputObject;
		itemID = elePageInput.getAttribute("SKU");
		isMil = elePageInput.getAttribute("MIL");
		initialize();
		setBindingForComponents();
        myBehavior = new XPXShowListOfUOMPanelBehaviour(this, FORM_ID, elePageInput);
	}
	
	private void initialize() {
		createRootPanel();
		this.setLayout(new FillLayout());
		setSize(new org.eclipse.swt.graphics.Point(600,400));
		createInfoComposite();
	}
	
	private void createInfoComposite() {
		GridLayout gridLayout1 = new GridLayout();
		gridLayout1.marginWidth = 1;
		gridLayout1.marginHeight = 1;

		GridData gridData = new GridData();
		gridData.horizontalAlignment = 4;
		gridData.grabExcessHorizontalSpace = true;
		gridData.grabExcessVerticalSpace = true;
		gridData.verticalAlignment = 4;
		pnlProfileInfo = new Composite(getRootPanel(), 0);
		pnlProfileInfo.setLayoutData(gridData);
		pnlProfileInfo.setLayout(gridLayout1);
		pnlProfileInfo.setData("name", "pnlProfileInfo");
		createPnlInfo();
		}
	
	private void createPnlInfo() {

		GridLayout srchGroupLayout = new GridLayout();
		GridData gdSrchGroup = new GridData();
		grpSearchFields = new Group(pnlProfileInfo, SWT.NONE);

		gdSrchGroup.grabExcessHorizontalSpace = true;
		gdSrchGroup.widthHint = 60;
		gdSrchGroup.horizontalAlignment = org.eclipse.swt.layout.GridData.FILL;
		grpSearchFields.setLayoutData(gdSrchGroup);
		grpSearchFields.setLayout(srchGroupLayout);
		//srchGroupLayout.marginHeight = 20;
		srchGroupLayout.numColumns = 4;
	
//Added for CustomerID
		
		lblItemName = new Label(grpSearchFields, SWT.NONE);
		lblItemName.setData(YRCConstants.YRC_CONTROL_NAME, "lblArticleName");
		lblItemName.setText("ITEM ID :");

		txtItemName = new Text(grpSearchFields, SWT.BORDER);
		txtItemName.setLayoutData(gdSrchGroup);
		txtItemName.setTextLimit(50);
		txtItemName.setData("name", "txtItemName");
		txtItemName.setText(itemID);
		txtItemName.setEditable(false);
		
		lblUOMID = new Label(grpSearchFields, SWT.NONE);
		lblUOMID.setData(YRCConstants.YRC_CONTROL_NAME, "lblArticleName");
		lblUOMID.setText("UOM ID");

		GridData gdListName = new GridData();
		gdListName.grabExcessHorizontalSpace = true;
		gdListName.horizontalSpan = 1;
		gdListName.horizontalAlignment = org.eclipse.swt.layout.GridData.FILL;
		
		uomIDCombo = new Combo(grpSearchFields, 8);
		uomIDCombo.setLayoutData(gdListName);
		uomIDCombo.setTextLimit(50);
		uomIDCombo.setData("name", "uomIDCombo");
		
		GridLayout srchBtnLayout = new GridLayout();
		GridData gdSrchBtnGroup = new GridData();
        grpBtnFields = new Group(pnlRoot, SWT.NONE);
        grpBtnFields.setLayoutData(gdSrchBtnGroup);
        grpBtnFields.setLayout(srchBtnLayout);
		//srchGroupLayout.marginHeight = 20;
		srchBtnLayout.numColumns = 2;
		
		Button btnUOMList = new Button(grpBtnFields, SWT.NONE);
		btnUOMList.setText("OK ");
		btnUOMList.addSelectionListener(new org.eclipse.swt.events.SelectionAdapter() { 
			public void widgetSelected(org.eclipse.swt.events.SelectionEvent e) {    
				myBehavior.getVal();
				getParent().getShell().close();
			}
		});
		
		Button btnUOMCancelList = new Button(grpBtnFields, SWT.NONE);
		btnUOMCancelList.setText("CANCEL");
		btnUOMCancelList.addSelectionListener(new org.eclipse.swt.events.SelectionAdapter() { 
			public void widgetSelected(org.eclipse.swt.events.SelectionEvent e) {    
				getParent().getShell().close();
			}
		});
	}
   
	public void setBindingForComponents(){
		
		YRCComboBindingData cbd = null;
		
		cbd = new YRCComboBindingData();
		cbd.setCodeBinding("@UomID");
		cbd.setDescriptionBinding("@UomDesc");
		cbd.setListBinding("UOMList:/Order/AlternateUOMList/AlternateUOM");
		cbd.setSourceBinding("UOMList:/Order/AlternateUOMList/AlternateUOM/@UomDesc");
		//cbd.setTargetBinding("XPXCustomercontactExtn:/CustomerContact/@ApproverUserId");
		cbd.setName("uomIDCombo");
		uomIDCombo.setData(YRCConstants.YRC_COMBO_BINDING_DEFINATION, cbd);
		
	}
    public String getFormId() {
        return FORM_ID;
    }
    
    public Composite getRootPanel() {
        return pnlRoot;
    }

	private void createRootPanel() {
		pnlRoot = new Composite(this, SWT.NONE);
        pnlRoot.setLayout(new GridLayout());
        
	}
	
	/**-------------------------------------------------***/
	
	private void createPnlTitleHolder() {
		XPXUtils.addGradientPanelHeader(pnlResults, "Customer Contact List", true);
	}
	
	private void createTblResults() {
	
	}
	
	
	
	public IYRCPanelHolder getPanelHolder() {
        // TODO Complete getPanelHolder
        return null;
    }
    
    public String getHelpId() {
		// TODO Complete getHelpId
		return null;
	}

	public Element getSelectedShipTo() {
		return eleSelected;
	}

	public XPXPaginationBehavior getPaginationBehavior() {
		return myBehavior;
	}


}
