	
/*
 * Created on Jul 29,2010
 *
 */
package com.xpedx.sterling.rcp.pca.sharedTasks.shiptolookup;

import org.eclipse.swt.events.MouseEvent;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.TableItem;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

import com.xpedx.sterling.rcp.pca.util.XPXPaginationBehavior;
import com.yantra.yfc.rcp.YRCApiContext;
import com.yantra.yfc.rcp.YRCPlatformUI;
import com.yantra.yfc.rcp.YRCXmlUtils;
import com.yantra.yfc.rcp.internal.YRCCommand;
import com.yantra.yfc.rcp.internal.YRCCommandRepository;

/**
 * @author sdodda
 *
 * Generated by Sterling RCP Tools
 */
 
public class XPXShowListOfShipToPanelBehavior extends XPXPaginationBehavior {

	public static final String PAGINATION_STRATEGY_FOR_SEARCH = NEXTPAGE_PAGINATION_STRATEGY;
	private static final String COMMAND_GET_LIST_OF_SHIPTO="XPXGetListOfAssignedShipTosForAUserService";
	private Element elePageInput;
	private XPXShowListOfShipToPanel page;

	/**
	 * Constructor for the behavior class. 
	 * @param elePageInput 
	 */
    public XPXShowListOfShipToPanelBehavior(Composite ownerComposite, String formId, Element elePageInput) {
        super(ownerComposite, formId);
        this.elePageInput = elePageInput;
        
        this.page = (XPXShowListOfShipToPanel)ownerComposite;
        initPage();
    }
    
	/**
	 * This method initializes the behavior class.
	 */    
	public void initPage() {
		
		if(null != elePageInput){

			Document input = YRCXmlUtils.createFromString("<XPXCustomerAssignmentView UserId='' ShipToAddressString='' ShipToAddressStringQryType='LIKE' Status='30' StatusQryType='NE'><OrderBy><Attribute Desc='N' Name='ShipToCustomerID' /></OrderBy></XPXCustomerAssignmentView>");
			/*Document input = YRCXmlUtils.createFromString("<XPXCustomerAssignmentView UserId='""' ShipToAddressString='""' ShipToAddressStringQryType='LIKE'>
					<OrderBy><Attribute Desc='N' Name='ShipToCustomerID' /></OrderBy></XPXCustomerAssignmentView>");
*/			
			input.getDocumentElement().setAttribute("UserId", elePageInput.getAttribute("UserID"));
			
			setModel("Input_getAssignedShipToList", input.getDocumentElement());
			if(!page.isDisposed()){
				setPaginationDetails(); 
				getFirstPage();
			}
		}
	}
	
	@Override
	public void handleApiCompletion(YRCApiContext apiContext) {
		if (apiContext.getInvokeAPIStatus() > 0){
			if (page.isDisposed()) {
				YRCPlatformUI.trace("Page is Disposed");
			} else {
				String[] apinames = apiContext.getApiNames();
				for (int i=0; i<apinames.length; i++) {
					String apiname = apinames[i];
					if(YRCPlatformUI.equals(apiname, "getPage")){
		     			Document docOutput = apiContext.getOutputXmls()[i];
						if (docOutput != null) {
							Element eleOutput = docOutput.getDocumentElement();
							//This is an inherited method which sets/replaces the model used to display the Paginated results.
							handlePaginationOutput(eleOutput);
						}
		     		}
				}
			}
		}
		super.handleApiCompletion(apiContext);
	}

	public void mouseDoubleClick(MouseEvent e, String string) {
		TableItem tblItems[] = page.tblResults.getSelection();
        if(tblItems.length > 0)
        	for(int i = 0; i < tblItems.length; i++)
                if(!YRCPlatformUI.isVoid(tblItems[i]) && !tblItems[i].isDisposed())
                {
                	
                	Element eleCustomer = (Element)tblItems[i].getData();
					Element eleAddress = YRCXmlUtils.createDocument("ShipTo").getDocumentElement();
					eleAddress.setAttribute("BuyerOrganizationCode", eleCustomer.getAttribute("ShipToCustomerID"));
					eleAddress.setAttribute("CustomerID", eleCustomer.getAttribute("ShipToCustomerID"));
					eleAddress.setAttribute("OrganizationName", eleCustomer.getAttribute("ShipToCustomerName"));
					eleAddress.setAttribute("MSAPCustomerID", eleCustomer.getAttribute("MSAPCustomerID"));
					eleAddress.setAttribute("SAPCustomerID", eleCustomer.getAttribute("SAPCustomerID"));
					eleAddress.setAttribute("BillToCustomerID", eleCustomer.getAttribute("BillToCustomerID"));
					eleAddress.setAttribute("BillToCustomerName", eleCustomer.getAttribute("BillToCustomerName"));
					eleAddress.setAttribute("ExtnCustStoreNo", eleCustomer.getAttribute("ShipToExtnCustStoreNo"));
					eleAddress.setAttribute("OrganizationCode", eleCustomer.getAttribute("EnterpriseCode"));
					eleAddress.setAttribute("AddressLine1", eleCustomer.getAttribute("AddressLine1"));
					eleAddress.setAttribute("AddressLine2", eleCustomer.getAttribute("AddressLine2"));
					eleAddress.setAttribute("AddressLine3", eleCustomer.getAttribute("AddressLine3"));
					eleAddress.setAttribute("City", eleCustomer.getAttribute("City"));
					eleAddress.setAttribute("Country", eleCustomer.getAttribute("Country"));
					eleAddress.setAttribute("DisplayAddressString", eleCustomer.getAttribute("ShipToAddressString"));
					eleAddress.setAttribute("State", eleCustomer.getAttribute("State"));
					eleAddress.setAttribute("ZipCode", eleCustomer.getAttribute("ZipCode"));
					if(!YRCPlatformUI.isVoid(eleCustomer.getAttribute("ExtnZip4")))
						eleAddress.setAttribute("Zip4", eleCustomer.getAttribute("ExtnZip4"));
					if(!YRCPlatformUI.isVoid(eleCustomer.getAttribute("EMailID")))
						eleAddress.setAttribute("EMailID", eleCustomer.getAttribute("EMailID"));
					if(!YRCPlatformUI.isVoid(eleCustomer.getAttribute("FirstName")))
						eleAddress.setAttribute("FirstName", eleCustomer.getAttribute("FirstName"));
					if(!YRCPlatformUI.isVoid(eleCustomer.getAttribute("LastName")))
						eleAddress.setAttribute("LastName", eleCustomer.getAttribute("LastName"));
                    this.page.eleSelected = eleAddress;
                    
                }
		
	}
	
	public void search() {
		this.getXpxPaginationData().setInputXml(getModel("Input_getAssignedShipToList").getOwnerDocument());
		super.search();
	}

	private void setPaginationDetails(){
		 
        this.getXpxPaginationData().setPaginationStrategy(PAGINATION_STRATEGY_FOR_SEARCH);
        
		YRCCommand command = YRCCommandRepository.getCommand((new StringBuilder()).append(getFormId()).append(COMMAND_GET_LIST_OF_SHIPTO).toString());
		this.getXpxPaginationData().setApiName(command.getCommandAPIName());
		this.getXpxPaginationData().setIsFlow("Y");
		
		//Set the model data. This is a pre-requisite before calling the handlePaginationOutput method
		setSrcModelName("XPXCustomerAssignmentViewList");
		setRootListElemName("XPXCustomerAssignmentViewList");
		setRepeatingElemName("XPXCustomerAssignmentView");
	}
	public void setRepeatingElemName(String repeatingElemName) {
		this.repeatingElemName = repeatingElemName;
	}

	public void setRootListElemName(String rootListElemName) {
		this.rootListElemName = rootListElemName;
	}

	public void setSrcModelName(String srcModelName) {
		this.srcModelName = srcModelName;
	}
	
	public void getVal() {
		TableItem tblItems[] = page.tblResults.getSelection();
		Element eleAddress = YRCXmlUtils.createDocument("ShipTo").getDocumentElement();
		StringBuffer sb = new StringBuffer();
		StringBuffer sap = new StringBuffer();
		StringBuffer msap= new StringBuffer();
		StringBuffer bt = new StringBuffer();
        if(tblItems.length > 0 && tblItems!=null)
        	for(int i = 0; i < tblItems.length; i++){
                if(!YRCPlatformUI.isVoid(tblItems[i]) && !tblItems[i].isDisposed())
                {
                	Element eleCustomer = (Element)tblItems[i].getData();
                
                 if(eleCustomer.getAttribute("ShipToCustomerID")!="" && eleCustomer.getAttribute("ShipToCustomerID")!=null)
                {
		           sb.append(eleCustomer.getAttribute("ShipToCustomerID") + ",");
                }   
                 
                 if(eleCustomer.getAttribute("MSAPCustomerID")!="" && eleCustomer.getAttribute("MSAPCustomerID")!=null)
                 {
 		           msap.append(eleCustomer.getAttribute("MSAPCustomerID") + ",");
                 }  
                 if(eleCustomer.getAttribute("SAPCustomerID")!="" && eleCustomer.getAttribute("SAPCustomerID")!=null)
                 {
 		           sap.append(eleCustomer.getAttribute("SAPCustomerID") + ",");
                 }   
                 if(eleCustomer.getAttribute("BillToCustomerID")!="" && eleCustomer.getAttribute("BillToCustomerID")!=null)
                 {
 		           bt.append(eleCustomer.getAttribute("BillToCustomerID") + ",");
                 } 
               
                }
        	}
        
        eleAddress.setAttribute("CustomerID", sb.toString());
        eleAddress.setAttribute("MSAPCustomerID", msap.toString());
        eleAddress.setAttribute("SAPCustomerID", sap.toString());
        eleAddress.setAttribute("BillToCustomerID", bt.toString());
        
        
        this.page.eleSelected = eleAddress;
	}

}
