package com.xpedx.sterling.rcp.pca.sharedTasks.shiptolookup;
import java.util.ArrayList;

import org.eclipse.swt.events.MouseEvent;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.TableItem;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

import com.xpedx.sterling.rcp.pca.util.XPXPaginationBehavior;
import com.yantra.yfc.rcp.YRCApiContext;
import com.yantra.yfc.rcp.YRCPlatformUI;
import com.yantra.yfc.rcp.YRCXmlUtils;
import com.yantra.yfc.rcp.internal.YRCCommand;
import com.yantra.yfc.rcp.internal.YRCCommandRepository;

/**
 * @author Manas
 *
 * Generated by Sterling RCP Tools
 */
public class XPXShowListOfUsersPanelBehaviour extends XPXPaginationBehavior{
	public static final String PAGINATION_STRATEGY_FOR_SEARCH = NEXTPAGE_PAGINATION_STRATEGY;
	private static final String COMMAND_GET_LIST_OF_SHIPTO="XPXGetListOfAssignedShipTosForAUserService";
	private Element elePageInput;
	private XPXShowListOfUsersPanel page;

	/**
	 * Constructor for the behavior class. 
	 * @param elePageInput 
	 */
    public XPXShowListOfUsersPanelBehaviour(Composite ownerComposite, String formId, Element elePageInput) {
        super(ownerComposite, formId);
        this.elePageInput = elePageInput;
        
        this.page = (XPXShowListOfUsersPanel)ownerComposite;
        initPage();
    }
    
	/**
	 * This method initializes the behavior class.
	 */    
	public void initPage() {
		
		if(null != elePageInput){
			String strRootCustomerKey = YRCXmlUtils.getAttribute(elePageInput, "CustomerKey");
			Document docInput = YRCXmlUtils.createFromString("<CustomerContact CustomerKey='"+strRootCustomerKey+"'/>");
			YRCApiContext apiCtx = new YRCApiContext();
			
				String[] apinames = {"getCustomerContactList"};
				
				apiCtx.setApiNames(apinames);
				apiCtx.setInputXml(docInput);
			
			apiCtx.setFormId(getFormId());
			callApi(apiCtx);
	}
	}
	@Override
	public void handleApiCompletion(YRCApiContext apiContext) {
		if (apiContext.getInvokeAPIStatus() > 0){
			if (page.isDisposed()) {
				YRCPlatformUI.trace("Page is Disposed");
			} else {
				String[] apinames = apiContext.getApiNames();
				for (int i=0; i<apinames.length; i++) {
					String apiname = apinames[i];
					if(YRCPlatformUI.equals(apiname, "getCustomerContactList")){
		     			Document docOutput = apiContext.getOutputXmls()[i];
						if (docOutput != null) {
							Element eleOutput = docOutput.getDocumentElement();
							//This is added to remove the dummy customer contacts
							 NodeList nodList=eleOutput.getElementsByTagName("CustomerContact");
							 ArrayList eSalesRepList = new ArrayList();
							 for(int k=0;k<nodList.getLength();k++){
								
								 Element  eleCust=(Element) nodList.item(k);
								 String customerID = eleCust.getAttribute("CustomerContactID");			
									Element statusElement = YRCXmlUtils.getXPathElement(eleCust, "/CustomerContact/Extn");
									String eSalesRep = statusElement.getAttribute("ExtnIsSalesRep");
									if("Y".equalsIgnoreCase(eSalesRep)){
										eSalesRepList.add(customerID);
									}
								 }
							 
							 // Added to remove the elements
							 NodeList nodeCustContact=eleOutput.getElementsByTagName("CustomerContact");
								for(int j=0;j<nodeCustContact.getLength();j++){
									Element elementCust=(Element) nodeCustContact.item(j);
									String customerID = elementCust.getAttribute("CustomerContactID");
									if (eSalesRepList.contains(customerID)){
										elementCust.getParentNode().removeChild(elementCust);
										j--;
									}
									
								}
							setModel("UserList",eleOutput);
						}
		     		}
				}
			}
		}
		//super.handleApiCompletion(apiContext);
	}

	public void mouseDoubleClick(MouseEvent e, String string) {
		TableItem tblItems[] = page.tblResults.getSelection();
        if(tblItems.length > 0)
        	for(int i = 0; i < tblItems.length; i++)
                if(!YRCPlatformUI.isVoid(tblItems[i]) && !tblItems[i].isDisposed())
                {
                	
                	Element eleCustomer = (Element)tblItems[i].getData();
					Element eleAddress = YRCXmlUtils.createDocument("XpedxMilBothLst").getDocumentElement();
					if(!YRCPlatformUI.isVoid(eleCustomer.getAttribute("CustomerContactID")))
						eleAddress.setAttribute("Createuserid", eleCustomer.getAttribute("CustomerContactID"));
                    this.page.eleSelected = eleAddress;
                    
                }
		
	}
	
	public void search() {
		this.getXpxPaginationData().setInputXml(getModel("Input_getAssignedShipToList").getOwnerDocument());
		super.search();
	}

	private void setPaginationDetails(){
		 
        this.getXpxPaginationData().setPaginationStrategy(PAGINATION_STRATEGY_FOR_SEARCH);
        
		YRCCommand command = YRCCommandRepository.getCommand((new StringBuilder()).append(getFormId()).append(COMMAND_GET_LIST_OF_SHIPTO).toString());
		this.getXpxPaginationData().setApiName(command.getCommandAPIName());
		this.getXpxPaginationData().setIsFlow("Y");
		
		//Set the model data. This is a pre-requisite before calling the handlePaginationOutput method
		setSrcModelName("XPXCustomerAssignmentViewList");
		setRootListElemName("XPXCustomerAssignmentViewList");
		setRepeatingElemName("XPXCustomerAssignmentView");
	}
	public void setRepeatingElemName(String repeatingElemName) {
		this.repeatingElemName = repeatingElemName;
	}

	public void setRootListElemName(String rootListElemName) {
		this.rootListElemName = rootListElemName;
	}

	public void setSrcModelName(String srcModelName) {
		this.srcModelName = srcModelName;
	}
	
	public void getVal() {
		TableItem tblItems[] = page.tblResults.getSelection();
		Element eleAddress = YRCXmlUtils.createDocument("ShipTo").getDocumentElement();
		StringBuffer sb = new StringBuffer();
		StringBuffer sap = new StringBuffer();
		StringBuffer msap= new StringBuffer();
		StringBuffer bt = new StringBuffer();
        if(tblItems.length > 0 && tblItems!=null)
        	for(int i = 0; i < tblItems.length; i++){
                if(!YRCPlatformUI.isVoid(tblItems[i]) && !tblItems[i].isDisposed())
                {
                	Element eleCustomer = (Element)tblItems[i].getData();
                
                 if(eleCustomer.getAttribute("ShipToCustomerID")!="" && eleCustomer.getAttribute("ShipToCustomerID")!=null)
                {
		           sb.append(eleCustomer.getAttribute("ShipToCustomerID") + ",");
                }   
                 
                 if(eleCustomer.getAttribute("MSAPCustomerID")!="" && eleCustomer.getAttribute("MSAPCustomerID")!=null)
                 {
 		           msap.append(eleCustomer.getAttribute("MSAPCustomerID") + ",");
                 }  
                 if(eleCustomer.getAttribute("SAPCustomerID")!="" && eleCustomer.getAttribute("SAPCustomerID")!=null)
                 {
 		           sap.append(eleCustomer.getAttribute("SAPCustomerID") + ",");
                 }   
                 if(eleCustomer.getAttribute("BillToCustomerID")!="" && eleCustomer.getAttribute("BillToCustomerID")!=null)
                 {
 		           bt.append(eleCustomer.getAttribute("BillToCustomerID") + ",");
                 } 
               
                }
        	}
        
        eleAddress.setAttribute("CustomerID", sb.toString());
        eleAddress.setAttribute("MSAPCustomerID", msap.toString());
        eleAddress.setAttribute("SAPCustomerID", sap.toString());
        eleAddress.setAttribute("BillToCustomerID", bt.toString());
        
        
        this.page.eleSelected = eleAddress;
	}

}
