
package zwm1.com.ipaper.xpedx.wm.web.priceavailability.wsipaperavailability;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "wsIpaperAvailability", targetNamespace = "http://zwm1/com/ipaper/xpedx/wm/web/priceavailability/wsIpaperAvailability", wsdlLocation = "http://wmclustert4.ipaper.com:15000/ws/com.ipaper.xpedx.wm.web.priceavailability:wsIpaperAvailability?WSDL")
public class WsIpaperAvailability
    extends Service
{

    private final static URL WSIPAPERAVAILABILITY_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(zwm1.com.ipaper.xpedx.wm.web.priceavailability.wsipaperavailability.WsIpaperAvailability.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = zwm1.com.ipaper.xpedx.wm.web.priceavailability.wsipaperavailability.WsIpaperAvailability.class.getResource(".");
            url = new URL(baseUrl, "http://wmclustert4.ipaper.com:15000/ws/com.ipaper.xpedx.wm.web.priceavailability:wsIpaperAvailability?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://wmclustert4.ipaper.com:15000/ws/com.ipaper.xpedx.wm.web.priceavailability:wsIpaperAvailability?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSIPAPERAVAILABILITY_WSDL_LOCATION = url;
    }

    public WsIpaperAvailability(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsIpaperAvailability() {
        super(WSIPAPERAVAILABILITY_WSDL_LOCATION, new QName("http://zwm1/com/ipaper/xpedx/wm/web/priceavailability/wsIpaperAvailability", "wsIpaperAvailability"));
    }

    /**
     * 
     * @return
     *     returns WsIpaperAvailabilityPortType
     */
    @WebEndpoint(name = "com_ipaper_xpedx_wm_web_priceavailability_wsIpaperAvailability_Port")
    public WsIpaperAvailabilityPortType getComIpaperXpedxWmWebPriceavailabilityWsIpaperAvailabilityPort() {
        return super.getPort(new QName("http://zwm1/com/ipaper/xpedx/wm/web/priceavailability/wsIpaperAvailability", "com_ipaper_xpedx_wm_web_priceavailability_wsIpaperAvailability_Port"), WsIpaperAvailabilityPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsIpaperAvailabilityPortType
     */
    @WebEndpoint(name = "com_ipaper_xpedx_wm_web_priceavailability_wsIpaperAvailability_Port")
    public WsIpaperAvailabilityPortType getComIpaperXpedxWmWebPriceavailabilityWsIpaperAvailabilityPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://zwm1/com/ipaper/xpedx/wm/web/priceavailability/wsIpaperAvailability", "com_ipaper_xpedx_wm_web_priceavailability_wsIpaperAvailability_Port"), WsIpaperAvailabilityPortType.class, features);
    }

}
