/* EB-5365 UPDATE SQL */
UPDATE  XPX_EMAIL_DEFN 
SET EMAIL_XSL_PATH='../extensions/global/template/email/XPX_Order_Confirmation.xsl' 
WHERE EMAIL_TYPE IN ('ORDER_APPROVED_EMAIL','ORDER_REJECTED_EMAIL','ORDER_PENDING_APPROVAL_EMAIL');

COMMIT;