CREATE OR REPLACE VIEW "NG"."XPEDX_MIL_BOTHLIST" 
AS
SELECT 
	MIL.MY_ITEMS_LIST_KEY,
    MIL.LIST_ORDER,
    MIL.CUSTOMER_ID,
    MIL.LIST_NAME,
	MIL.LIST_DESC,
    MIL.CREATEUSERNAME,
    MIL.CREATEUSERID,
    MIL.MODIFYUSERID,
    MIL.CREATEPROGID,
    MIL.MODIFYPROGID,
    MIL.SHARE_ADMIN_ONLY,
    MIL.SHARE_PRIVATE,
    MIL.MODIFYTS,
    CUST.CUSTOMER_KEY,
    CUST.PARENT_CUSTOMER_KEY,
    CUST.ROOT_CUSTOMER_KEY,
    CUST.EXTN_CUSTOMER_DIVISION,
    CUST.EXTN_SUFFIX_TYPE

from xpedx_my_items_list MIL, yfs_customer CUST
where trim(MIL.Customer_id) = trim(CUST.Customer_id)
