CREATE OR REPLACE VIEW "NG"."XPEDX_MIL_BOTHLIST" 
AS
SELECT 
    MIL.MY_ITEMS_LIST_KEY,
    MIL.CUSTOMER_ID,
    MIL.LIST_NAME,
    MIL.LIST_DESC,
    MIL.CREATEUSERNAME,
    MIL.CREATEUSERID,
    MIL.MODIFYUSERID,
    MIL.SHARE_ADMIN_ONLY,
    MIL.SHARE_PRIVATE,
    MIL.MODIFYTS,
	MIL.LIST_ORDER,
    CUST.CUSTOMER_KEY,
    CUST.PARENT_CUSTOMER_KEY,
    CUST.ROOT_CUSTOMER_KEY,
    CUST.EXTN_SUFFIX_TYPE,
    CUST.EXTN_CUSTOMER_DIVISION,
    NVL(MILS.MY_ITEMS_LIST_SHARE_KEY,'99999') AS MY_ITEMS_LIST_SHARE_KEY,
    MILS.CUSTOMER_ID AS SHARE_CUSTOMER_ID,
    MILS.CUSTOMER_PATH,
    ORG.ORGANIZATION_NAME,
    ORG.ORGANIZATION_CODE,
    COUNT(MY_ITEMS_KEY) AS TOTALITEMS
FROM xpedx_my_items_list MIL
inner join yfs_customer CUST on (MIL.Customer_id) = trim(CUST.Customer_id)
INNER JOIN xpedx_my_items_items ITEM on trim(MIL.MY_ITEMS_LIST_KEY) = trim(ITEm.MY_ITEMS_LIST_KEY)
LEFT OUTER JOIN xpedx_my_items_list_share MILS ON trim(MIL.MY_ITEMS_LIST_KEY) = trim(mils.MY_ITEMS_LIST_KEY)
LEFT OUTER JOIN yfs_organization ORG ON trim(cust.EXTN_CUSTOMER_DIVISION) = replace(trim(ORG.organization_code),'_M','')

GROUP BY
    MIL.MY_ITEMS_LIST_KEY,
    MIL.CUSTOMER_ID,
    MIL.LIST_NAME,
    MIL.LIST_DESC,
    MIL.CREATEUSERNAME,
    MIL.CREATEUSERID,
    MIL.MODIFYUSERID,
    MIL.SHARE_ADMIN_ONLY,
    MIL.SHARE_PRIVATE,
    MIL.MODIFYTS,
    CUST.CUSTOMER_KEY,
    CUST.PARENT_CUSTOMER_KEY,
    CUST.ROOT_CUSTOMER_KEY,
    CUST.EXTN_SUFFIX_TYPE,
    CUST.EXTN_CUSTOMER_DIVISION,
    MILS.MY_ITEMS_LIST_SHARE_KEY,
    MILS.CUSTOMER_ID,
    MILS.CUSTOMER_PATH,
    ORG.ORGANIZATION_NAME,
    ORG.ORGANIZATION_CODE

