CREATE INDEX "NG"."XPX_YFS_ORDER_HEADER_I20" ON "NG"."YFS_ORDER_HEADER"
(
"EXTN_WEB_CONF_NUM", "EXTN_LEGACY_ORDER_NO"
);

CREATE INDEX "NG"."XPX_YFS_CUSTOMER_I5" ON "NG"."YFS_CUSTOMER"
(
  "EXTN_LEGACY_CUST_NUMBER", "EXTN_SHIP_TO_SUFFIX", "EXTN_SUFFIX_TYPE", "ORGANIZATION_CODE"
);
  
CREATE INDEX "NG"."XPX_YFS_CUSTOMER_ASSGN_I4" ON "NG"."YFS_CUSTOMER_ASSIGNMENT"
(
  "CUSTOMER_KEY", "ASSIGNMENT_TYPE"
); 