	
/*
 * Created on Jul 19,2010
 *
 */
package com.xpedx.sterling.rcp.pca.divisionMaintainance.screen;

import org.eclipse.swt.widgets.Composite;

import com.yantra.yfc.rcp.YRCBehavior;

/**
 * @author sdodda
 *
 * Generated by Sterling RCP Tools
 */
 
public class DivisionMaintenanceTabFolderPanelBehavior extends YRCBehavior {

	/**
	 * Constructor for the behavior class. 
	 * @param inputObject 
	 */
	 
    public DivisionMaintenanceTabFolderPanelBehavior(Composite ownerComposite, String formId, Object inputObject) {
        super(ownerComposite, formId);
        init();
    }
    
	/**
	 * This method initializes the behavior class.
	 */    
	public void init() {
		//TODO: write behavior init here
	}

}
