	
/*
 * Created on Apr 14,2010
 *
 */
package com.xpedx.sterling.rcp.pca.userprofile.editor;

import org.eclipse.core.runtime.IConfigurationElement;
import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.swt.SWT;
import org.eclipse.swt.widgets.Composite;
import org.w3c.dom.Element;

import com.xpedx.sterling.rcp.pca.customercontact.extn.CustomerContactWizardExtnBehavior;
import com.xpedx.sterling.rcp.pca.orderlines.wizard.XPXOrderLinesWizardBehavior;
import com.xpedx.sterling.rcp.pca.userprofile.screen.UserProfileMaintenance;
import com.yantra.yfc.rcp.YRCConstants;
import com.yantra.yfc.rcp.YRCDesktopUI;
import com.yantra.yfc.rcp.YRCEditorInput;
import com.yantra.yfc.rcp.YRCEditorPart;
import com.yantra.yfc.rcp.YRCPlatformUI;
import com.yantra.yfc.rcp.YRCRelatedTask;
import com.yantra.yfc.rcp.YRCWizard;
import com.yantra.yfc.rcp.YRCXmlUtils;

/**
 * @author sdodda
 *
 * Generated by MTCE
 */

public class XPXUserProfileEditor extends YRCEditorPart {

	public static final String ID_EDITOR = "com.xpedx.sterling.rcp.pca.customerprofilerule.editor.XPXUserProfileEditor";
    private Composite pnlRoot;
    private String userID;


    @Override
	protected boolean acceptTask(YRCRelatedTask task) {
		return super.acceptTask(task);
	}

	@Override
	public void setInitializationData(IConfigurationElement cfig,
			String propertyName, Object data) {
		super.setInitializationData(cfig, propertyName, data);
	}

	@Override
	protected void setPartName(String partName) {
		super.setPartName(partName);
	}
	
	public void doSave(IProgressMonitor monitor) {
    }

    public void doSaveAs() {
    }

    public boolean isDirty() {
        return false;
    }

    public boolean isSaveAsAllowed() {
        return false;
    }

    public Composite createPartControl(Composite parent, String taskID) {
    	YRCEditorInput input = (YRCEditorInput)getEditorInput();
        input.setTaskName(taskID);
        Element ele = input.getXml();
        userID = YRCXmlUtils.getAttribute(ele, "UserID");
        Composite currentPage = YRCDesktopUI.getCurrentPage();
        Element customerContactEle= ((CustomerContactWizardExtnBehavior)(((YRCWizard) currentPage).getExtensionBehavior())).getLocalModel("getCustomerContactDetails_output");
        pnlRoot = new UserProfileMaintenance(parent, SWT.NONE,input,customerContactEle);
        pnlRoot.setData(YRCConstants.YRC_OWNERPART, this);
        setPartName(getTitleKey()+" "+userID);        
    	return pnlRoot;
    }

    public void postSetFocus() {
        pnlRoot.setFocus();
    }

    public void showBusy(boolean busy) {
        if (busy) {
            setPartName(YRCPlatformUI.getString("wait_title"));
            pnlRoot.setCursor(YRCPlatformUI.getCursor(SWT.CURSOR_WAIT));
        }
        else {
            setPartName(getTitleKey());
            pnlRoot.setCursor(null);
        }
    }
    private String getTitleKey()
    {
        return "User Profile";
    }
     
}
