
package zwm1.com.ipaper.xpedx.wm.web.orderplacement.wsipaperplaceorder;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "wsIpaperPlaceOrder_PortType", targetNamespace = "http://zwm1/com/ipaper/xpedx/wm/web/orderplacement/wsIpaperPlaceOrder")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsIpaperPlaceOrderPortType {


    /**
     * 
     * @param wsIpaperPlaceOrderInput
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "com_ipaper_xpedx_wm_web_orderplacement_wsIpaperPlaceOrder_Binder_fPlaceOrder")
    @WebResult(name = "wsIpaperPlaceOrderOutput", targetNamespace = "")
    @RequestWrapper(localName = "fPlaceOrder", targetNamespace = "http://zwm1/com/ipaper/xpedx/wm/web/orderplacement/wsIpaperPlaceOrder", className = "zwm1.com.ipaper.xpedx.wm.web.orderplacement.wsipaperplaceorder.FPlaceOrder")
    @ResponseWrapper(localName = "fPlaceOrderResponse", targetNamespace = "http://zwm1/com/ipaper/xpedx/wm/web/orderplacement/wsIpaperPlaceOrder", className = "zwm1.com.ipaper.xpedx.wm.web.orderplacement.wsipaperplaceorder.FPlaceOrderResponse")
    public String fPlaceOrder(
        @WebParam(name = "wsIpaperPlaceOrderInput", targetNamespace = "")
        String wsIpaperPlaceOrderInput);

}
