
package zwm1.com.ipaper.xpedx.wm.web.orderplacement.wsipaperplaceorder;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.yantra.yfs.core.YFSSystem;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */

@WebServiceClient(name = "wsIpaperPlaceOrder", targetNamespace = "http://zwm1/com/ipaper/xpedx/wm/web/orderplacement/wsIpaperPlaceOrder", wsdlLocation = "http://wmclustert4.ipaper.com:15000/ws/com.ipaper.xpedx.wm.web.orderplacement:wsIpaperPlaceOrder?WSDL")
public class WsIpaperPlaceOrder
    extends Service
{

    private final static URL WSIPAPERPLACEORDER_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(zwm1.com.ipaper.xpedx.wm.web.orderplacement.wsipaperplaceorder.WsIpaperPlaceOrder.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = zwm1.com.ipaper.xpedx.wm.web.orderplacement.wsipaperplaceorder.WsIpaperPlaceOrder.class.getResource(".");
            String endPointURL=YFSSystem.getProperty("OrderPlaceWSDL")+"?WSDL";;
            url = new URL(baseUrl, endPointURL/*endPointURL"http://wmclustert4.ipaper.com:15000/ws/com.ipaper.xpedx.wm.web.orderplacement:wsIpaperPlaceOrder?WSDL"*/);
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: http://wmclustert4.ipaper.com:15000/ws/com.ipaper.xpedx.wm.web.orderplacement:wsIpaperPlaceOrder?WSDL, retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSIPAPERPLACEORDER_WSDL_LOCATION = url;
    }

    public WsIpaperPlaceOrder(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsIpaperPlaceOrder() {
        super(WSIPAPERPLACEORDER_WSDL_LOCATION, new QName("http://zwm1/com/ipaper/xpedx/wm/web/orderplacement/wsIpaperPlaceOrder", "wsIpaperPlaceOrder"));
    }

    /**
     * 
     * @return
     *     returns WsIpaperPlaceOrderPortType
     */
    @WebEndpoint(name = "com_ipaper_xpedx_wm_web_orderplacement_wsIpaperPlaceOrder_Port")
    public WsIpaperPlaceOrderPortType getComIpaperXpedxWmWebOrderplacementWsIpaperPlaceOrderPort() {
        return super.getPort(new QName("http://zwm1/com/ipaper/xpedx/wm/web/orderplacement/wsIpaperPlaceOrder", "com_ipaper_xpedx_wm_web_orderplacement_wsIpaperPlaceOrder_Port"), WsIpaperPlaceOrderPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsIpaperPlaceOrderPortType
     */
    @WebEndpoint(name = "com_ipaper_xpedx_wm_web_orderplacement_wsIpaperPlaceOrder_Port")
    public WsIpaperPlaceOrderPortType getComIpaperXpedxWmWebOrderplacementWsIpaperPlaceOrderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://zwm1/com/ipaper/xpedx/wm/web/orderplacement/wsIpaperPlaceOrder", "com_ipaper_xpedx_wm_web_orderplacement_wsIpaperPlaceOrder_Port"), WsIpaperPlaceOrderPortType.class, features);
    }

}
